name: 'transactions_dbt'
version: '1.0.0'
config-version: 2

profile: 'transactions_dbt'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transactions_dbt:
    staging:
      +materialized: view
      +schema: transactions
      +data_tests:
        unique:
          +severity: error
        not_null:
          +severity: error
    intermediate:
      +materialized: view
      +schema: transactions
    marts:
      +materialized: table
      +schema: transactions
      +data_tests:
        unique:
          +severity: error
        not_null:
          +severity: error