transactions_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      location: US